//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QBMidicon.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QBMidicon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   QBMidicon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonMoveBottom {
            get {
                return ResourceManager.GetString("ButtonMoveBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonMoveDown {
            get {
                return ResourceManager.GetString("ButtonMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonMoveTop {
            get {
                return ResourceManager.GetString("ButtonMoveTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonMoveUp {
            get {
                return ResourceManager.GetString("ButtonMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonOpenFile {
            get {
                return ResourceManager.GetString("ButtonOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonSearch {
            get {
                return ResourceManager.GetString("ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Selected {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to clear it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClearConfirm {
            get {
                return ResourceManager.GetString("ClearConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compress Forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompressForward {
            get {
                return ResourceManager.GetString("CompressForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please correct the error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConfirmSaveHasError {
            get {
                return ResourceManager.GetString("ConfirmSaveHasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compress Forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextKitPitchesCompressForward {
            get {
                return ResourceManager.GetString("ContextKitPitchesCompressForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Text To Clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextKitPitchesCopyTextToClipBoard {
            get {
                return ResourceManager.GetString("ContextKitPitchesCopyTextToClipBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Selected {0} &apos;{1}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Fill に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DialogAutomaticFill {
            get {
                return ResourceManager.GetString("DialogAutomaticFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is already in use! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Not Found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About QBMidicon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Current Contents Are Discarded. Do You Still Want To Execute? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewFileConfirm {
            get {
                return ResourceManager.GetString("NewFileConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste Complete! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteComplete {
            get {
                return ResourceManager.GetString("PasteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to run the paste? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteConfirm {
            get {
                return ResourceManager.GetString("PasteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid clipboard content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteError {
            get {
                return ResourceManager.GetString("PasteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accent Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingAccentColor {
            get {
                return ResourceManager.GetString("SettingAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingLanguage {
            get {
                return ResourceManager.GetString("SettingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingPageTitle {
            get {
                return ResourceManager.GetString("SettingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Up Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingStartUpPage {
            get {
                return ResourceManager.GetString("SettingStartUpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open or close navigation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellMainPage {
            get {
                return ResourceManager.GetString("ShellMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellSettingPage {
            get {
                return ResourceManager.GetString("ShellSettingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ConvertedDataPage {
            get {
                return ResourceManager.GetString("Title_ConvertedDataPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_ConvertSettingPage {
            get {
                return ResourceManager.GetString("Title_ConvertSettingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event Filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_EventFilterPage {
            get {
                return ResourceManager.GetString("Title_EventFilterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_SourceDataPage {
            get {
                return ResourceManager.GetString("Title_SourceDataPage", resourceCulture);
            }
        }
    }
}
